### ISSUE TITLE
couldn't execute commands

### ISSUE THREAD

**Issue by Code-shaker** [yoursunny/NDNts-video-server#2]
```text
node ./cli.cjs prepare --prefix $VIDEO_PREFIX --path $VIDEO_TEMP > video.dtar
EnvironmentVariableError: REPO_PATH is required but is not set
    at getValue (/home/vmadmin/NDNts-video-server/node_modules/.pnpm/@strattadb+environment@8.0.2/node_modules/@strattadb/environment/dist/environment.js:40:13)
    at /home/vmadmin/NDNts-video-server/node_modules/.pnpm/@strattadb+environment@8.0.2/node_modules/@strattadb/environment/dist/environment.js:20:19
    at Array.reduce (<anonymous>)
    at makeEnv (/home/vmadmin/NDNts-video-server/node_modules/.pnpm/@strattadb+environment@8.0.2/node_modules/@strattadb/environment/dist/environment.js:19:38)
    at file:///home/vmadmin/NDNts-video-server/src/env.js:9:20
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
```

**Comment by yoursunny** [comment]
Did you copy `sample.env` to `.env`, as indicated in the instructions?

**Comment by Code-shaker** [comment]
yes I overlook this step, thanks

**Comment by yoursunny** [comment]
I just did an update (commit 48cb10f2f943d768aeb7bc8898107b82fc2d0992): adding a postinstall step that copies `sample.env` to `.env` if it does not already exist.
