### ISSUE TITLE
NDNts-video-server running on MiniNDN: "Error: Not supported"

### ISSUE THREAD

**Issue by matianxing1992** [yoursunny/NDNts-video-server#5]
I succeeded in making everything work on my local system. When I turned to MiniNDN, the settings are the same but I was faced with this problem:

```text
Error: Not supported
    at Object.<anonymous> (/tmp/minindn/drone1/NDNts-video-server/cli.cjs:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```
Can you give me hints about it? Thank you very much!

**Comment by yoursunny** [comment]
I can tell that you are trying to run `cli.cjs` and there's a "not supported" exception.
`cli.cjs` itself does not contain code that would throw this exception.
If another module is throwing this exception, it should show up in the stacktrace.

My guess is that you are invoking a different version of Node.js in the Mininet container than what's installed on the host machine.
This is very likely the case if you installed Node.js with Node Version Manager (nvm), because nvm-installed Node.js is only effective in the current user, and would not apply to Mininet container.

To confirm whether this is the case, run the following commands on both the host machine and in the Mininet container:

* `node -v`
* `corepack -v`

If they have different output on the host machine vs the Mininet container, you can confirm this is the case.

After confirming, please report back and I can give further instructions.

**Comment by matianxing1992** [comment]
Yes, I got "node -v: v10.19.0","corepack -v:command not found" with MiniNDN, and ""node -vv16.14.2 corepack -v 0.10.0" on my local machine. I think it's pre-intalled in the MiniNDN.

**Comment by yoursunny** [comment]
Neither Mininet nor Mini-NDN pre-installs Node.js.
Mininet is not a full containerization solution, and it would use the system-wide Node.js installation.
To upgrade the system-wide Node.js installation, you may use [deb.nodesource.com](https://github.com/nodesource/distributions).
NDNts-video-server supports both 16.x and 17.x.

**Comment by matianxing1992** [comment]
Thank you for your instructions! I followed them and solved this problem. I really appreciate it!
